# Generated by Django 6.1.1 on 2026-09-22 17:13

import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('universities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_photo_path)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('phone_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('email_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('dob_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='HIDDEN', max_length=10)),
                ('district_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('upazila_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('organization_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('facebook_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('linkedin_visibility', models.CharField(choices=[('VISIBLE', 'Visible'), ('HIDDEN', 'Hidden')], default='VISIBLE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.batch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.district')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.division')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.session')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universities.university')),
                ('upazila', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.upazila')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
